### ISSUE TITLE
Cast problems with BSONCollection

### ISSUE THREAD

**Issue by benkio** [themillhousegroup/play2-reactivemongo-mocks#1]
Hello, 
First of all i want say thanks for your work :)
I'm trying to use your library to mock reactivemongo but I used the BSONCollection as type for db collection so i come up with this error when i try to run some test.
java.lang.ClassCastException: play.modules.reactivemongo.json.collection.JSONCollection$$EnhancerByMockitoWithCGLIB$$98c2d9b2 cannot be cast to reactivemongo.api.collections.bson.BSONCollection

There's a workaround for this?
If it can help, here there's the stack trace: http://pastebin.com/4JQWDHWB
and here the code of my test: https://github.com/benkio/DomoticRoom/blob/Server/Server/test/persistenceStore/persistenceStoreTest.scala

**Comment by themillhousegroup** [comment]
Hi Enrico,
Sorry about the delay in getting back to you, I was on holiday all last
week!

Glad to see you trying out the mocks library - but as you've discovered,
it's very-much geared towards using the Play JSON API and the
JSONCollection that is supplied by ReactiveMongo.

I attempted to use generics to support the BSONCollection as well as the
JSONCollection but it quickly became impossible as there is a whole family
of other objects required (QueryBuilders etc) all of which need to be
specified :-(

Having a look at your code, as you're using Play, have you considered using
the JSONCollection provided by the Play ReactiveMongo pack:
https://github.com/reactivemongo/reactivemongo-play-json? If you switch to
using it, the mocks library will work great and also you'll be able to
specify your queries using Play JSON (for example in
https://github.com/benkio/DomoticRoom/blob/master/Server/app/models/persistenceStore/loaders/PersistenceStoreRangeLoader.scala
).

Best of luck with your project, and sorry I wasn't able to offer a solution.

Best Regards,
John Marshall
The Millhouse Group

**Comment by benkio** [comment]
Hi,
Thanks for the reply, 
i will consider you suggestion.
I take advantage to signal you this dependency problem, due to the version of specs2, i encountered importing your library in a new project:

http://stackoverflow.com/questions/35944390/play-framework-2-4-withapplication-call-not-found-in-play-api-test

if you want i can open an issue for a better way of track that.
Best Regards
Enrico

**Comment by themillhousegroup** [comment]
Hi Enrico,
It would be fantastic if you could open another issue for that. I'm pretty
certain I can get a fixed version out very quickly.

I'll close this issue (#1) as "won't fix".

Thanks again,
John
