### ISSUE TITLE
Specs2 Dependency Problem in New project

### ISSUE THREAD

**Issue by benkio** [themillhousegroup/play2-reactivemongo-mocks#2]
I start a new project with play 2.4.6 and the newer version of specs2 (3.6) but i encountered a dependency problem due to an old specs2 depencency in the play2-reactivemongo-mocks as you can see here:

http://stackoverflow.com/questions/35944390/play-framework-2-4-withapplication-call-not-found-in-play-api-test

**Comment by themillhousegroup** [comment]
Hi Enrico,
Should be all fixed now; this library now expects a specs2 with version 3.6 or higher to be _provided_ - should work perfectly with Play 2.4.x.

Just change the version number of play2-reactivemongo-mocks in your `build.sbt` to the one now showing in README.md - i.e. ending in **_0.5.33**
